### ISSUE TITLE
Namespace Error When Building My Project

### ISSUE THREAD

**Issue by siempus** [Servalstar/Easy-Icon-Maker#1]
First of all, this is not really a major issue, but every time i tried to build my project Unity throws error due to "PreviewRenderUtility" namespace which is part of UnityEditor. I realized that Easy-Icon-Maker is not intended to be run outside editor environment. I'm not completely sure how to exclude scripts from the build so i did add "#if UNITY_EDITOR" directive at the beginning of the script and "#endif" directive at the end of the script. I did this to all the scripts of Easy-Icon-Maker. Basically, making all the scripts only run in the editor environment. This way, i can successfully build my project without any issue.

**Comment by Servalstar** [comment]
Hello, Jeffrey. Thanks for the comment.
I added directives and corrected the description.
