### ISSUE TITLE
Distorted icons

### ISSUE THREAD

**Issue by Orthopoxvirus** [Servalstar/Easy-Icon-Maker#2]
Hey, I love the simplicity of the tool but I'm having an issue where the generated icon is distorted:

Final icon:
![fe_vil_wagons_a_cart01A](https://github.com/Servalstar/Easy-Icon-Maker/assets/22443072/697d1411-49fe-44d5-95bf-46dedc102f25)

Setting:
![Screenshot 2023-07-29 212417](https://github.com/Servalstar/Easy-Icon-Maker/assets/22443072/b6fa694b-82e3-409c-a22d-a237c216ab28)

Any idea why? I'm using unity 2022.3

**Comment by Servalstar** [comment]
Hi. Sorry for the late answer.
I couldn't reproduce your issue with distortion in Unity 2022.3.3f1, but fixed another issue with scaling rendering in texture. Maybe this update will help you.

**Comment by Orthopoxvirus** [comment]
Hey, I tried the new version. The distortion is indeed fixed and the messed up URP preview consist, but that does not matter. Thanks 👌
